#!/bin/bash
#SBATCH --ntasks=1 
#SBATCH --partition=ampere
#SBATCH --error=warp_tm_part_export.err
#SBATCH --output=warp_tm_part_export.out
#SBATCH --job-name=warp
#SBATCH --mem-per-cpu=18GB
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --time=1-00:00:00

# Load WarpTools
module load warpem


# Define variables
settings="warp_tiltseries.settings"
input_directory="warp_tiltseries/matching"
relative_output_paths=true # Set to true to include --relative_output_paths

# Variables to edit
input_pattern="*MT14PF_4nm_clean.star"
output_star="relion_14PF_4nm/matching.star"
output_angpix=4.24
box=160
diameter=380
output_processing="warp_tiltseries/particleseries" # If you want different output folder


# Run WarpTools ts_export_particles with specified settings
WarpTools ts_export_particles \
  --settings "$settings" \
  --input_directory $input_directory \
  --input_pattern $input_pattern \
  --normalized_coords \
  --output_star "$output_star" \
  --output_angpix "$output_angpix" \
  --box "$box" \
  --diameter "$diameter" \
  --2d \
  --output_processing "$output_processing" \
  $( [ "$relative_output_paths" = true ] && echo "--relative_output_paths" )




