#!/bin/bash
#SBATCH --ntasks=1 
#SBATCH --partition=titan
#SBATCH --error=warp_rel5_part_export.err
#SBATCH --output=warp_rel5_part_export.out
#SBATCH --job-name=warp
#SBATCH --mem-per-cpu=18GB
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --time=1-00:00:00


# Load WarpTools
module load warpem

# Define variables
settings="warp_tiltseries.settings"

# Variables to edit
input_star="doublet_2/coord_96nm.star"
output_star="relion/coord_96nm.star"
coords_angpix=8.48
output_angpix=8.48
box=168
n_tilts=32 # This makes it safer
diameter=1000
output_processing="warp_tiltseries/particleseries" # If you want different output folder


# Run WarpTools ts_export_particles with specified settings
WarpTools ts_export_particles \
  --settings "$settings" \
  --input_star "$input_star" \
  --output_star "$output_star" \
  --coords_angpix "$coords_angpix" \
  --output_angpix "$output_angpix" \
  --box "$box" \
  --diameter "$diameter" \
  --n_tilts "$n_tilts" \
  --output_processing "$output_processing" \
  --relative_output_paths \
  --2d \





