#!/bin/bash
#SBATCH --ntasks=1 
#SBATCH --partition=ampere
#SBATCH --error=warp_tm_particles_export.err
#SBATCH --output=warp_tm_particles_export.out
#SBATCH --job-name=warp
#SBATCH --mem-per-cpu=18GB
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1


WarpTools ts_export_particles \
--settings warp_tiltseries.settings \
--input_directory warp_tiltseries/matching \
--input_pattern "*MT14PF_4nm_clean.star" \
--normalized_coords \
--output_star relion_14PF_4nm/matching.star \
--output_angpix 4.24 \
--box 160 \
--diameter 380 \
--relative_output_paths \
--2d

