#!/bin/bash
#SBATCH --ntasks=1 
#SBATCH --partition=cpu
#SBATCH --error=warp_ts_import_aln.err
#SBATCH --output=warp_ts_import_aln.out
#SBATCH --job-name=warp
#SBATCH --mem-per-cpu=18GB
#SBATCH --cpus-per-task=4
#SBATCH --nodes=1
#SBATCH --time=1-00:00:00


# Load WarpTools
module load warpem

# Import alignment
settings="warp_tiltseries.settings"
alignments="warp_tiltseries/tiltstack/"

# Variable to edit
alignment_angpix=2.12 # If import for IMOD old data, use unbinned pixel size

# Empty quote "" for all, 1 tomogram only  like "tomostar/SPEF1MT2_018.tomostar"
input_data=""

# Run WarpTools ts_import_alignments with specified settings
WarpTools ts_import_alignments \
  --settings "$settings" \
  --alignments "$alignments" \
  --alignment_angpix "$alignment_angpix" \
  $( [ -n "$input_data" ] && echo "--input_data $input_data" )

