#!/bin/bash
#SBATCH --ntasks=1 
#SBATCH --partition=titan
#SBATCH --error=warp_rel5_part_import.err
#SBATCH --output=warp_rel5_part_import.out
#SBATCH --job-name=warp
#SBATCH --mem-per-cpu=18GB
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1


# Load WarpTools
module load warpem

# Define variables
settings="warp_tiltseries.settings"

# Variables to edit
input_star="doublet_2/coord_96nm.star"
output_star="relion/coord_96nm.star"
coords_angpix=8.48
output_angpix=8.48
box=168
diameter=1000

# Run WarpTools ts_export_particles with specified settings
WarpTools ts_export_particles \
  --settings "$settings" \
  --input_star "$input_star" \
  --output_star "$output_star" \
  --coords_angpix "$coords_angpix" \
  --output_angpix "$output_angpix" \
  --box "$box" \
  --diameter "$diameter" \
  --relative_output_paths \
  --2d




