#!/bin/bash
#SBATCH --ntasks=1 
#SBATCH --partition=cpu
#SBATCH --error=warp_framesetting.err
#SBATCH --output=warp_framesetting.out
#SBATCH --job-name=warp
#SBATCH --mem-per-cpu=18GB
#SBATCH --cpus-per-task=4
#SBATCH --nodes=1


WarpTools create_settings --folder_data Frames --folder_processing warp_frameseries --output warp_frameseries.settings --extension "*.tif" --angpix 2.12 --gain_path Frames/CountRef_SPEF1MT2_00000_0.0.mrc --gain_flip_y --exposure 4

